# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: double-quote-string-fixer
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf
        additional_dependencies:
          - toml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
      - id: ruff
        args: [--fix]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.1.1'
  #   hooks:
  #     - id: mypy
