name: "Install Python and DIANNA"
description: "Installs Python, updates pip and installs DIANNA together with its dependencies."
inputs:
  python-version:
    required: false
    description: "The Python version to use. Specify major and minor version, e.g. '3.9'."
    default: "3.9"
  extras-require:
    required: false
    description: "The extras dependencies packages to be installed, for instance 'docs' or 'publishing,notebooks'."

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@v3
      id: cache-python-env
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}

    - name: Python info
      shell: bash {0}
      run: |
        which python3
        python --version

    - name: Upgrade pip
      if: steps.cache-python-env.outputs.cache-hit != 'true'
      shell: bash {0}
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # only necessary on linux to avoid bloated installs
    - name: Install tensorflow/pytorch cpu version
      if: runner.os == 'Linux' && steps.cache-python-env.outputs.cache-hit != 'true'
      shell: bash {0}
      run: |
        python -m pip install torch --index-url https://download.pytorch.org/whl/cpu
        python -m pip install tensorflow-cpu

    - name: Install DIANNA
      if: steps.cache-python-env.outputs.cache-hit != 'true'
      shell: bash {0}
      run: |
        python -m pip install -e .[dev]

    - name: Install DIANNA extras
      if: ${{ inputs.extras-require }}
      shell: bash {0}
      run: |
        python -m pip install -e .[${{ inputs.extras-require }}]
