name: "Install Python and DIANNA"
description: "Installs Python, updates pip and installs DIANNA together with its dependencies."
inputs:
  python-version:
    required: false
    description: "The Python version to use. Specify major and minor version, e.g. '3.9'."
    default: "3.9"
  extras-require:
    required: false
    description: "The extras dependencies packages to be installed, for instance 'dev' or 'dev,publishing,notebooks'."
    default: "dev"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}

    - name: Python info
      shell: bash {0}
      run: |
        which python3
        python3 --version

    - name: Upgrade pip and install dependencies
      shell: bash {0}
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip install torch https://download.pytorch.org/whl/cpu
        pip install tensorflow-cpu
        python3 -m pip install -e .[${{ inputs.extras-require }}]
