name: fair-software

on:
  workflow_dispatch:
  push:
    branches:
    - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  pull_request:
    branches:
    - main

jobs:
  verify_main:
    name: "fair-software"
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: fair-software/howfairis-github-action@0.2.1
        name: Measure compliance with fair-software.eu recommendations
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output" 
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
  verify_pull_request:
    name: "fair-software"
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: fair-software/howfairis-github-action@0.2.1
        name: Measure compliance with fair-software.eu recommendations
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output" 
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}/refs/remotes/pull/${{ github.event.pull_request.number }}/merge"
