name: linting

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

jobs:

  build:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install additional dependencies
        run: |
          pip install ruff

      - name: Check code style
        run: |
          ruff dianna tests
