name: notebooks

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:

  notebooks:
    name: Run notebooks on (${{ matrix.python-version }}, ${{ matrix.os }})
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-and-package
        with:
          python-version: ${{ matrix.python-version }}
          extras-require: dev,notebooks
      - name: Run tutorial notebooks
        run: pytest --nbmake tutorials
