name: notebooks

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  list_notebooks:
    name: List notebooks
    runs-on: 'ubuntu-latest'
    outputs:
      notebooks: ${{ steps.list_notebooks.outputs.notebooks }}
    steps:
      - uses: actions/checkout@v6
      - name: List notebooks
        id: list_notebooks
        run: |
          NOTEBOOKS_JSON=$(find tutorials -type f -name "*.ipynb" | python -c 'import json,sys; print(json.dumps([line.strip() for line in sys.stdin if line.strip()]))')
          echo "Found notebooks: $NOTEBOOKS_JSON"
          echo "notebooks=$NOTEBOOKS_JSON" >> "$GITHUB_OUTPUT"

  run_notebook:
    name: Run notebook ${{ matrix.notebook }} on (${{ matrix.python-version }}, ${{ matrix.os }})
    if: github.event.pull_request.draft == false
    needs: list_notebooks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.11']
        notebook: ${{ fromJson(needs.list_notebooks.outputs.notebooks) }}
        exclude:
          - os: 'windows-latest'
            notebook: 'tutorials/explainers/KernelSHAP/kernelshap_tabular_land_atmosphere.ipynb' # this one fails on Windows due to timeouts, not sure why, see #877
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install-python-and-package
        with:
          python-version: ${{ matrix.python-version }}
          extras-require: dev,notebooks
      # Workaround for xgboost OpenMP issue on macOS (see https://github.com/dmlc/xgboost/pull/12108).
      # Once that PR is included in a released version of xgboost, this step can be removed.
      - name: Install OpenMP runtime (macOS)
        if: runner.os == 'macOS'
        run: brew install libomp
      - name: Run tutorial notebook
        run: pytest --nbmake "${{ matrix.notebook }}"
